- hosts: all
  tasks:

  - package:
      name: "{{ package_httpd }}"
      state: latest

  - package:
      name: "{{ package_unzip }}"
      state: latest

  - systemd:
     name: "{{ service_httpd }}"
     state: started  

  - name: Download a Template
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page296/carvilla.zip
      dest: /tmp/carvilla.zip

  - name: Extract Template
    unarchive:
      src: /tmp/carvilla.zip
      dest: /tmp/
      remote_src: yes

  - name: Move Template to /var/www/html
    shell: mv /tmp/carvilla-v1.0/* /var/www/html/  
    args:
      creates: /var/www/html/readme.txt